export default [
  {value: 'Fantasy', key: 'Fantasy'},
  {value: 'Magic', key: 'Magic'},
  {value: 'Mystery', key: 'Mystery'},
  {value: 'Crime', key: 'Crime'},
  {value: 'Thriller', key: 'Thriller'},
  {value: 'Adult', key: 'Adult'},
  {value: 'Romance', key: 'Romance'},
  {value: 'Fiction', key: 'Fiction'},
  {value: 'Young adult', key: 'Young adult'},
  {value: 'Classic', key: 'Classic'},
  {value: 'Literature', key: 'Literature'},
  {value: 'Adventure', key: 'Adventure'},
  {value: 'Science Fiction', key: 'Science Fiction'},
  {value: 'Dark fantasy', key: 'Dark fantasy'},
  {value: 'Historical', key: 'Historical'},
  {value: 'Horror', key: 'Horror'},
];
